# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "08cf4da352007849224a6eaca315b4b9"
name = "qr-code-generator"
application_url = "https://pr-send-retail-herself.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-webential-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://pr-send-retail-herself.trycloudflare.com/auth/callback",
  "https://pr-send-retail-herself.trycloudflare.com/auth/shopify/callback",
  "https://pr-send-retail-herself.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
